### ISSUE TITLE
Does it support Swift 3 ? Does it have animation speed control feature?

### ISSUE THREAD

**Issue by kristoff2016** [khanxc/KXThumbCircularProgressBar#16]
Hi it would be great if support swift 3.

**Comment by khanxc** [comment]
@kristoff2016  Yes it does support, please open an issue if you are facing any.

**Comment by kristoff2016** [comment]
#17  I want to custom use in my app as music for progress bar. it does ?

**Comment by kristoff2016** [comment]
it is very nice that I am looking for like this

**Comment by khanxc** [comment]
@kristoff2016 Yes you have to control the animation speed property according to your custom needs. Glad it helped.

**Comment by kristoff2016** [comment]
Thank you so much

**Comment by kristoff2016** [comment]
Hi, Progressbar does not update. I have used   progressView.animateScale = CurrentSongProgressbar 
I still not see any progressbar update
