### ISSUE TITLE
Request: Could you add featured progress bar Value ?

### ISSUE THREAD

**Issue by kristoff2016** [khanxc/KXThumbCircularProgressBar#18]
Hello, thank you for sharing very nice lib. I very liked your lib but what I stuck right now I can not add value to progress bar. thanks

**Comment by kristoff2016** [comment]
@khanxc

**Comment by Ibrahim32** [comment]
Hi @kristoff2016 
You can find the animateScale in IBInspectable property. Enter the animateScale value from 0 to 1.

**Comment by kristoff2016** [comment]
Hi, I knew it but your lib animateScale value from 0 to 1 just load only when viewDidload. it is not possible to make it update during my song playing for update this animateScale
