### ISSUE TITLE
Does it have animation speed control feature?

### ISSUE THREAD

**Issue by akshay-shah-dev** [khanxc/KXThumbCircularProgressBar#20]

**Comment by Ibrahim32** [comment]
As for now animation speed control feature available in library level.
pathAnimation.duration = 2
animation.duration = 2

**Comment by akshay-shah-dev** [comment]
I have try to change value of  these two prop but its not affected in output

**Comment by akshay-shah-dev** [comment]
any other option available?

**Comment by Ibrahim32** [comment]
i tried in the example project, changing the duration of those two properties.
Its working fine.
        pathAnimation.duration = 10
        animation.duration = 10
if you want to slow down the animation, increase the duration value as you wanted.
